SWARMHOME=../..
LIBNAME=simtoolsgui

OBJECTS=ControlPanel.o GUISwarm.o ProbeDisplay.o CommonProbeDisplay.o SimpleProbeDisplay.o CompleteProbeDisplay.o VarProbeWidget.o MessageProbeWidget.o ClassDisplayWidget.o ProbeDisplayManager.o ActiveGraph.o ActionCache.o ActionHolder.o GUIComposite.o simtoolsgui.o

HEADERS=ControlPanel.h GUISwarm.h ProbeDisplay.h CommonProbeDisplay.h SimpleProbeDisplay.h CompleteProbeDisplay.h VarProbeWidget.h MessageProbeWidget.h ClassDisplayWidget.h ProbeDisplayManager.h ActiveGraph.h ActionCache.h ActionHolder.h GUIComposite.h global.h

include $(SWARMHOME)/Makefile.lib

ControlPanel.o: ControlPanel.m ControlPanel.h
GUISwarm.o: GUISwarm.m GUISwarm.h
ProbeDisplay.o: ProbeDisplay.m ProbeDisplay.h
CommonProbeDisplay.o: CommonProbeDisplay.m CommonProbeDisplay.h
SimpleProbeDisplay.o: SimpleProbeDisplay.m SimpleProbeDisplay.h
CompleteProbeDisplay.o: CompleteProbeDisplay.m CompleteProbeDisplay.h
VarProbeWidget.o: VarProbeWidget.m VarProbeWidget.h
MessageProbeWidget.o: MessageProbeWidget.m MessageProbeWidget.h
ClassDisplayWidget.o: ClassDisplayWidget.m ClassDisplayWidget.h
ProbeDisplayManager.o: ProbeDisplayManager.m ProbeDisplayManager.h
ActiveGraph.o: ActiveGraph.m ActiveGraph.h
ActionCache.o: ActionCache.h ActionCache.m
ActionHolder.o: ActionHolder.h ActionHolder.m
GUIComposite.o: GUIComposite.h GUIComposite.m
simtoolsgui.o: simtoolsgui.h simtoolsgui.m