JAVA_SRC = Heatbug.java HeatCell.java HeatSpace.java HeatbugModelSwarm.java  HeatbugObserverSwarm.java StartHeatbug.java # HeatbugBatchSwarm.java 

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)

clean: 
	- rm -f $(wildcard *.class)







