#!/bin/sh
. $SWARMHOME/etc/swarm/config.swarm

LD_LIBRARY_PATH=`sort <<EOF 2>/dev/null | uniq | tr '\012' ':'
$swarm_libdir
$xpmlibdir
$tcllibdir
$tklibdir
$bltlibdir
$ffilibdir
$pnglibdir
$zliblibdir
EOF`$LD_LIBRARY_PATH

if test -z "$1" ; then
  echo $LD_LIBRARY_PATH
else
  export LD_LIBRARY_PATH
  java -classpath ${swarm_datadir}/swarm/swarm.jar $*
fi

