#!/bin/sh
. $SWARMHOME/etc/swarm/config.swarm

LD_LIBRARY_PATH=`sort 2>/dev/null | uniq | tr '\012' ':' <<EOF
$swarm_libdir
$xpmlibdir
$tcllibdir
$tklibdir
$bltlibdir
$ffilibdir
$pnglibdir
$zliblibdir
EOF`$LD_LIBRARY_PATH

export LD_LIBRARY_PATH

java $*

