#!/bin/sh
. $SWARMHOME/etc/swarm/config.swarm

if test x$JAVA_CLASSES_INSTALLED_AS = xjar; then
  classpath=".:${swarm_datadir}/swarm/swarm.jar:${JAVACLASSES}:$CLASSPATH"
else
  classpath=".:${swarm_datadir}:${JAVACLASSES}:$CLASSPATH"
fi

eval "$JAVAC -classpath $classpath $*"

