#!/bin/sh
. $SWARMHOME/etc/swarm/config.swarm

if test $JAVA_CLASSES_INSTALLED_AS = jar; then
  classpath=".:${swarm_datadir}/swarm/swarm.jar:${JAVACLASSES}:$CLASSPATH"
else
  classpath=".:${swarm_datadir}:${JAVACLASSES}:$CLASSPATH"
fi

eval "$JAVA -classpath $classpath pizza.compiler.Main $*"

