#!/bin/sh

# Copyright © 2000 Swarm Development Group
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
# 
# The Swarm Development Group can be reached via our website at:
# http://www.swarm.org/

JDKPATH=`regtool get 'HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.3\JavaHome' 2>/dev/null`
if test -n "$JDKPATH"; then
  JDKPATH=`cygpath -u $JDKPATH`
  classpath=".;${SWARMDIR}"'\share\swarm\swarm.jar;'"${SWARMDIR}"'\share\swarm\kawa.jar'";$CLASSPATH"
 
  for i in "$@"; do
    argsexpr="$argsexpr '$i'"
  done
  if test -n "$JAVASWARMGDB"; then
    echo "set args $argsexpr" > /tmp/.swarmgdbinit.$$
    eval "CLASSPATH='$classpath' $JAVASWARMGDB -command /tmp/.swarmgdbinit.$$ $JDKPATH/bin/java"
    rm -f /tmp/.swarmgdbinit.$$
  else
    CLASSPATH="$classpath" $JDKPATH/bin/java $*
  fi
else
  echo "JDK 1.3 does not appear to be installed" 1>&2
fi

