JAVA_SRC = SimpleBug.java ModelSwarm.java FoodSpace.java StartSimpleBug.java

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)

clean: 
	rm -f *.class

cleanall:
	rm -f *.class
	rm -f *.java~






