JADE = @JADE@
JADETEX = @JADETEX@
DVIPS = @DVIPS@
GZIP = gzip --best
top_dossrcdir = @top_dossrcdir@

HTML = $(top_dossrcdir)/html.dsl
PRINT = $(top_dossrcdir)/print.dsl
JADEFLAGS = -V biblio-citation-check

RUNJADE = $(JADE) $(JADEFLAGS)
CATOPTS = -c $(top_builddir)/catalog  @catopts@ 

FIGS = figs/swarm.eps # for the timestamp

GENERAL = $(SGML_FILES) $(COMMON_SGML_FILES) $(top_srcdir)/common.dsl $(FIGS)

.PHONY: fot tex dvi ps rtf html htmldist dvidist psdist rtfdist alldist

alldist: htmldist dvidist rtfdist psdist

COMMON_SGML_FILES = $(top_srcdir)/figs/figs.ent $(top_srcdir)/global.ent $(top_builddir)/versions.ent

DISTNAME=$(NAME)-@VERSION@

htmldir = $(prefix)/html/$(NAME)
nodist_html_DATA = $(wildcard *.html) 

install-data-local:
	$(INSTALL_DATA) $(filter-out $(NAME).html,$(wildcard *.html)) $(htmldir)
install-data-hook:
	(cd $(htmldir) && $(LN_S) -f $(prefix)/figs figs)

uninstall-local:
	- (cd $(htmldir); rm -rf *)	

userbookdir:
	$(LN_S) -f `pwd` ../$(NAME)

.PHONY: userbookdir

htmldist: html userbookdir
	cd ..; tar cf -  $(addprefix $(NAME)/, $(wildcard *.html)) $(NAME)/figs | $(GZIP) > $(DISTNAME)-html.tar.gz

dvidir = $(prefix)/dvi
nodist_dvi_DATA = $(NAME).dvi

dvidist: dvi userbookdir
	cd .. ; tar cf - $(NAME)/$(NAME).dvi $(NAME)/figs | $(GZIP) > $(DISTNAME)-dvi.tar.gz

psdir = $(prefix)/ps
nodist_ps_DATA = $(NAME).ps

psdist: ps userbookdir
	$(GZIP) < $(NAME).ps > ../$(DISTNAME).ps.gz

rtfdir = $(prefix)/rtf
nodist_rtf_DATA = $(NAME).rtf

rtfdist: rtf distdir
	cd .. ; tar cf - $(NAME)/$(NAME).rtf $(NAME)/figs | $(GZIP) > $(DISTNAME)-rtf.tar.gz 

CLEANFILES = $(NAME).tex _$(NAME).tex $(nodist_html_DATA) $(nodist_dvi_DATA) $(nodist_ps_DATA) $(nodist_rtf_DATA)

$(FIGS):
	$(MAKE) -C $(top_builddir)/figs install figsdir=`pwd`/figs

_$(NAME).tex $(addprefix $(NAME),.fot .rtf): $(GENERAL) $(PRINT)

$(NAME).html: $(GENERAL) $(HTML)

$(NAME).dvi: $(top_srcdir)/tex/macros.tex

all-recursive: # when no SUBDIRS

fot: all-recursive $(NAME).fot

tex: all-recursive _$(NAME).tex

dvi: all-recursive $(NAME).dvi

ps: all-recursive $(NAME).ps 

rtf: all-recursive $(NAME).rtf

html: all-recursive $(NAME).html

%.fot: %.sgml
	$(RUNJADE) $(CATOPTS) -t fot -iprint -d $(PRINT) -o $@ `echo $< | sed 's,//\\([A-Za-z]\\),\1:,'`

_%.tex: %.sgml
	$(RUNJADE) $(CATOPTS) -V tex-backend -t tex -iprint -d $(PRINT) -o $@ `echo $< | sed 's,//\\([A-Za-z]\\),\\1:,'`

%.rtf: %.sgml
	$(RUNJADE) $(CATOPTS) -t rtf -iprint -d $(PRINT) -o $@ `echo $< | sed 's,//\\([A-Za-z]\\),\\1:,'`

%.html: %.sgml
	$(RUNJADE) $(CATOPTS) -t sgml -ihtml -d $(HTML) `echo $< | sed 's,//\([A-Za-z]\),\1:,'`

%.dvi: %.tex _%.tex
	- $(JADETEX) $< ; $(JADETEX) $< ; $(JADETEX) $<

%.ps: %.dvi
	$(DVIPS) -o $@ $<

# Local variables:
# mode: makefile
# end:
