#define STRINGIFY(sym) #sym
#define STRINGIFYSYM(sym) STRINGIFY(sym)
#define APPNAME_STRING STRINGIFYSYM(APPNAME)
#ifdef APPVERSION
#define APPVERSION_STRING STRINGIFYSYM(APPVERSION)
#else
#define APPVERSION_STRING NULL
#endif
#ifdef BUGADDRESS
#define BUGADDRESS_STRING STRINGIFYSYM(BUGADDRESS)
#else
#define BUGADDRESS_STRING NULL
#endif
