SWARMHOME=../..
LIBNAME=simtools
OBJECTS=simtools.o UName.o InFile.o ObjectLoader.o OutFile.o AppendFile.o ObjectSaver.o ActiveOutFile.o QSort.o NSelect.o Archiver.o

HEADERS=UName.h InFile.h ObjectLoader.h OutFile.h AppendFile.h ObjectSaver.h ActiveOutFile.h QSort.h NSelect.h Archiver.h

include $(SWARMHOME)/Makefile.lib

simtools.o: simtools.m
UName.o: UName.m UName.h
InFile.o: InFile.m InFile.h
ObjectLoader.o: ObjectLoader.m ObjectLoader.h
OutFile.o: OutFile.m OutFile.h
AppendFile.o:AppendFile.m AppendFile.h 
ObjectSaver.o: ObjectSaver.m ObjectSaver.h
ActiveOutFile.o: ActiveOutFile.m ActiveOutFile.h
QSort.o: QSort.m QSort.h
NSelect.o: NSelect.m NSelect.h
Archiver.o: Archiver.h Archiver.m
