.PHONY: headers

MAKEH2X = $(top_srcdir)/src/defobj/make-h2x

SUFFIXES = .m

TYPEINFO = $(MODULE).xm types.h classes.h

CLEANFILES = $(TYPEINFO)

headers: $(module_headers)

$(TYPEINFO): $(MODULE).h $(MAKEH2X)
	OBJC="$(OBJC)" OBJCFLAGS="$(DEFS) $(INCLUDES) $(CPPFLAGS) $(OBJCFLAGS)" OBJECTS="$(lib$(MODULE)_la_OBJECTS)" sh $(MAKEH2X) $(MODULE).xm $(srcdir)
	mv $(MODULE).xt types.h
	mv $(MODULE).xc classes.h

include_HEADERS = $(MODULE).h
