.PHONY: headers

SUFFIXES = .m

# Solaris JNI headers have some pragmas
override CFLAGS += @CFLAGS_NOWARN_UNKNOWN_PRAGMAS@
override OBJCFLAGS += @CFLAGS_NOWARN_UNKNOWN_PRAGMAS@

# We are building Swarm 
override CPPFLAGS += -DBUILDING_SWARM

CLEANFILES = $(TYPEINFO)

MAKEH2X = $(top_srcdir)/src/defobj/make-h2x

TYPEINFO = $(MODULE).xm types.h classes.h

xm_file = $(firstword $(BUILT_SOURCES))
$(filter-out $(xm_file),$(BUILT_SOURCES)): $(xm_file)

headers: $(xm_file)

$(firstword $(TYPEINFO)): $(MODULE).h $(MAKEH2X) # $(SOURCES)
	OBJC="$(OBJC)" OBJCFLAGS='$(DEFS) $(INCLUDES) $(CPPFLAGS) $(OBJCFLAGS)' OBJECTS="$(lib$(MODULE)_la_OBJECTS)" sh $(MAKEH2X) $(MODULE).xm $(srcdir)
	mv $(MODULE).xt types.h
	mv $(MODULE).xc classes.h

include_HEADERS = $(MODULE).h

# Local variables:
# mode: makefile
# End: