.PHONY: headers

SUFFIXES = .m

override CPPFLAGS += -DBUILDING_SWARM

CLEANFILES = $(TYPEINFO)

MAKEH2X = $(top_srcdir)/src/defobj/make-h2x

TYPEINFO = $(MODULE).xm types.h classes.h

headers: $(firstword $(BUILT_SOURCES))

$(firstword $(TYPEINFO)): $(MODULE).h $(MAKEH2X) # $(SOURCES)
	OBJC="$(OBJC)" OBJCFLAGS='$(DEFS) $(INCLUDES) $(CPPFLAGS) $(OBJCFLAGS)' OBJECTS="$(lib$(MODULE)_la_OBJECTS)" sh $(MAKEH2X) $(MODULE).xm $(srcdir)
	mv $(MODULE).xt types.h
	mv $(MODULE).xc classes.h

include_HEADERS = $(MODULE).h
