.PHONY: headers

MAKEH2X = $(top_srcdir)/src/defobj/make-h2x

SUFFIXES = .m

TYPEINFO = $(MODULE).xm $(MODULE)/types.h $(MODULE)/classes.h

CLEANFILES = $(TYPEINFO)

headers: $(TYPEINFO)

$(TYPEINFO): $(MODULE).h $(MAKEH2X) # $(SOURCES)
	OBJC="$(OBJC)" OBJCFLAGS="$(DEFS) $(INCLUDES) $(CPPFLAGS) $(OBJCFLAGS)" OBJECTS="$(patsubst %.m,%.o,$(filter-out %.h,$(type_SOURCES)))" sh $(MAKEH2X) $(MODULE).xm $(srcdir)
	test -d $(MODULE) || mkdir $(MODULE)
	mv $(MODULE).xt $(MODULE)/types.h
	mv $(MODULE).xc $(MODULE)/classes.h

include_HEADERS = $(MODULE).h
