.PHONY: headers swarm-link

MAKEH2X = $(top_srcdir)/src/defobj/make-h2x

SUFFIXES = .m

TYPEINFO = $(MODULE).xm $(MODULE)/$(MODULE)_types.h $(MODULE)/$(MODULE)_classes.h

CLEANFILES = $(TYPEINFO)

headers: $(firstword $(TYPEINFO))

swarm-link:
	-rm -f Swarm
	-$(LN_S) . Swarm

$(firstword $(TYPEINFO)): $(MODULE).h $(MAKEH2X) # $(SOURCES)
	OBJC="$(OBJC)" OBJCFLAGS="$(DEFS) $(INCLUDES) $(CPPFLAGS) $(OBJCFLAGS)" OBJECTS="$(patsubst %.m,%.o,$(filter-out %.h,$(type_SRCS)))" SED="$(SED)" sh $(MAKEH2X) $(MODULE).xm $(srcdir)
	test -d $(MODULE) || mkdir $(MODULE)
	mv $(MODULE).xt $(MODULE)/$(MODULE)_types.h
	mv $(MODULE).xc $(MODULE)/$(MODULE)_classes.h

