SWARMHOME=../..
LIBNAME=analysis
OBJECTS=Averager.o EZBin.o EZDistribution.o EZGraph.o Entropy.o 
HEADERS=Averager.h EZBin.h EZDistribution.h EZGraph.h Entropy.h 

include $(SWARMHOME)/Makefile.lib

Averager.o: Averager.m Averager.h 
Entropy.o: Entropy.m Entropy.h
EZGraph.o: EZGraph.m EZGraph.h
EZBin.o: EZBin.m EZBin.h
EZDistribution.o: EZDistribution.m EZDistribution.h
