JAVA_SRC = StartSimpleBug.java ExperSwarm.java ParameterManager.java ModelSwarm.java SimpleBug.java FoodSpace.java SwarmUtils.java

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)

clean: 
	rm -f *.class

cleanall:
	rm -f *.class
	rm -f *~
	rm *.stackdump








