JADE=jade
EMACS=emacs
JADETEX=jadetex
DVIPS=dvips
#DSSSLDIR=/net/wijiji/disk2/src/docbook
DSSSLDIR=/opt/src/alex/src/Swarm/swarmdocs

clean:
	rm -f *.htm  *.rtf *.tex *.fot *.dvi *.ps *.log *.aux

.PHONY: pages

# pattern rules for generating output files

%.fot : %.sgml
	- $(JADE) -t fot -d  $(DSSSLDIR)/swarmbook.dsl $<
%.rtf. : %.sgml
	- $(JADE) -t rtf -d $(DSSSLDIR)/swarmbook.dsl\#print $<
%.html : %.sgml
	- $(JADE) -t sgml -ihtml -d $(DSSSLDIR)/swarmbook.dsl\#html $<
%.tex : %.sgml
	- $(JADE) -t tex -d $(DSSSLDIR)/swarmbook.dsl\#print $<
%.dvi : %.tex
	- $(JADETEX) $< ; $(JADETEX) $<
%.ps : %.dvi
	- $(DVIPS) -o $@ $<

