JADE = jade
JADETEX = jadetex
DVIPS = dvips
EMACS = emacs

$(addsuffix $(NAME),.fot .htm .tex .dvi .ps .rtf): $(SGML_FILES)

fot: $(NAME).fot

tex: _$(NAME).tex

dvi: $(NAME).dvi

ps: $(NAME).ps

rtf: $(NAME).rtf

html: $(NAME).htm

%.fot: %.sgml
	 $(JADE) -t fot -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $< 

_%.tex: %.sgml
	- $(JADE) -t tex -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $<

%.rtf: %.sgml
	 $(JADE) -t rtf -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $<

%.dvi: %.tex _%.tex
	$(JADETEX) $< ; $(JADETEX) $< 

%.ps: %.dvi
	$(DVIPS) -o $@ $<

%.htm: %.sgml
	- $(JADE) -t sgml -ihtml -d $(top_srcdir)/swarmbook.dsl\#html $<

%revhistory.sgml: ChangeLog $(SWARMHOME)/src/%/ChangeLog
	SWARMDOCS_BUILD_AREA=$(top_builddir) $(EMACS) -batch -l $(top_srcdir)/history.el -f process-changelog $*
