JADE = jade
JADETEX = jadetex
DVIPS = dvips
EMACS = emacs

.PHONY: fot tex dvi ps rtf html

$(addprefix $(NAME),.fot .htm .tex .dvi .ps .rtf): $(SGML_FILES) $(top_srcdir)/common.dsl $(top_srcdir)/swarmbook.dsl

fot: all $(NAME).fot

tex: all _$(NAME).tex

dvi: all $(NAME).dvi

ps: all $(NAME).ps

rtf: all $(NAME).rtf

html: all $(NAME).htm

%.fot: %.sgml
	 $(JADE) -t fot -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $< 

_%.tex: %.sgml
	- $(JADE) -t tex -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $<

%.rtf: %.sgml
	 $(JADE) -t rtf -d $(top_srcdir)/swarmbook.dsl\#print -o $@ $<

%.dvi: %.tex _%.tex
	$(JADETEX) $< ; $(JADETEX) $< 

%.ps: %.dvi
	$(DVIPS) -o $@ $<

%.htm: %.sgml
	- $(JADE) -t sgml -ihtml -d $(top_srcdir)/swarmbook.dsl\#html $<

%revhistory.sgml: ChangeLog $(SWARMHOME)/src/%/ChangeLog $(top_srcdir)/history.el $(top_srcdir)/common.el
	SWARMDOCS=`cd $(top_srcdir); pwd`/ SWARMDOCS_BUILD_AREA=$(top_builddir)/ $(EMACS) -batch -l $(top_srcdir)/history.el -f process-changelog $*
