### Configure this file so Swarm knows about your environment. Some day
###   we will try to use GNU autoconf to do this for you.

### SETUP:  Canned setup for sites that build architecture-specific.  
### binaries (normal user use NONE and assign values to OTHERLIBDIRS
### and OTHERINCDIRS).  legal values: (NONE,SFI,nelson,umich);

### OTHERINCDIRS needs to be set so Swarm can find X11, tcl, tk, 
###   libtclobjc, and objc include files. Ie, <X11/Xlib.h>, <tcl.h>,
###   and <objc/Object.h> all need to be includable.
###

### OTHERLIBDIRS needs to be set so Swarm can find X11, Tcl, Tk, BLT,
###   tclobjc, libffi, and objc libs. 

### OTHERLIBS are other libraries you might need to link to compile
###   Swarm code. (-lsocket, for instance, or maybe -liberty).

### SYS: Induce canned options for a supported platform.  
### legal values: (solaris,hpux,linux,sgi)

### LDCONFIG: Use the distributed binary Swarm kernel (which has relevant
### portions of several system libraries linked into it), or use the
### local swarm library archives, along with local system libraries.
### legal values: (bin,archive)

VERSION=$(shell head -1 $(SWARMHOME)/VERSION)

ifeq ($(SWARMBACKEND),)
SWARMBACKEND=tk
endif

ifeq ($(SWARMSETUP),)
# Select your setup here, set SETUP in the environment, or provide
# a value on the command line.
SETUP=SFI
else
SETUP=$(SWARMSETUP)
endif

### for SETUP=NONE
SYS=
OTHERINCDIRS=
OTHERLIBDIRS=
SYSDEPLIBS=

LDCONFIG=archive

ifeq ($(SETUP),SFI)
# SFI's setup
SYS=solaris
CC=/opt/gnu/bin/gcc
XPREFIX=/opt/X11R6
FFPREFIX=/usr/local
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
ifeq ($(SWARMBACKEND),tk)
TCLVERS=7.6
TCLPREFIX=/usr/local
TKVERS=4.2
TKPREFIX=/usr/local
BLTVERS=2.3
BLTPREFIX=/usr/local/blt$(BLTVERS)
TCLOBJCPREFIX=/usr/local

TCLINCDIR=$(TCLPREFIX)/include/tcl$(TCLVERS)
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKINCDIR=$(TKPREFIX)/include/tk$(TKVERS)
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib/blt$(BLTVERS)
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib

PNGPREFIX=$(P)/graphics/png
PNGLIBDIR=$(PNGPREFIX)/lib
PNGINCDIR=$(PNGPREFIX)/include
ZPREFIX=$(P)/development/zlib
ZLIBDIR=$(ZPREFIX)/lib
ZINCDIR=$(ZPREFIX)/include

OTHERINCDIRS=-I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR)
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(TCLOBJCLIBDIR) -L$(BLTLIBDIR)/.. -L$(TKLIBDIR)/.. -L$(TCLLIBDIR)/.. -L$(XLIBDIR) 
override EXTRALDFLAGS+=-R$(BLTLIBDIR)/.. -R$(FFLIBDIR)
else
override EXTRACFLAGS+=-DUSE_JAVA
JAVALIBDIR=$(JAVA_HOME)/lib/sparc
JAVAINCDIR=$(JAVA_HOME)/include
OTHERINCDIRS=-I$(FFINCDIR) -I$(JAVAINCDIR) -I$(JAVAINCDIR)/solaris -I$(XINCDIR)
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(JAVALIBDIR)/$(JAVA_THREADS)_threads -L$(JAVALIBDIR) -L$(XLIBDIR)
override EXTRALDFLAGS+=-R$(JAVALIBDIR)
JAVAC=$(JAVA_HOME)/bin/javac
endif

OPTFLAGS=-O3 -g -mv8
endif

ifeq ($(SETUP),SFI-NT)
SYS=NT
P=$(SWARMROOT)/packages
CC=gcc
TCLVERS=80
TKVERS=80
BLTVERS=8.0-unoff
OPTFLAGS=-O3 -g
CYGSHARE=$(CYGFS)/share
TCLINCDIR=$(CYGFS)/include
TCLLIBDIR=$(CYGSHARE)/tcl8.0
TKINCDIR=$(CYGFS)/include
TKLIBDIR=$(CYGSHARE)/tk8.0
BLTPREFIX=$(P)/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib
BLTLIB=-lBLT80
TCLOBJCPREFIX=$(P)/tclobjc
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
ifeq (1,1)
FFPREFIX=$(P)/libffi
else
override EXTRACFLAGS+=-DUSE_AVCALL
FFPREFIX=$(P)/ffcall
FFLIB=-lavcall
endif
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
PNGPREFIX=$(P)/graphics/png
PNGLIBDIR=$(PNGPREFIX)/lib
PNGINCDIR=$(PNGPREFIX)/include
ZPREFIX=$(P)/development/zlib
ZLIBDIR=$(ZPREFIX)/lib
ZINCDIR=$(ZPREFIX)/include
OTHERINCDIRS= -I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR)
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(BLTLIBDIR) -L$(TCLOBJCLIBDIR)
override EXTRACFLAGS+=-Werror -Wno-sign-compare
endif  

ifeq ($(SETUP),alex-SFI-Solaris)
SYS=solaris
ifeq ($(SWARMCOMPILER),gcc28)
CC=$(P)/development/gcc/bin/gcc
OPTFLAGS=-mcpu=ultrasparc -O3 -g
override EXTRACFLAGS+=-Werror -Wno-implicit-int
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0-gcc28
else
ifeq ($(SWARMCOMPILER),egcs)
CC=$(P)/development/egcs/bin/gcc
OPTFLAGS= -mcpu=ultrasparc -O3 -g
override EXTRACFLAGS+=-Werror -Wno-implicit
TCLOBJCPREFIX=$(P)/swarm/tclobjc-egcs
else
CC=/opt/gnu/bin/gcc
OPTFLAGS=-O3 -g -mv8
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0-gcc
endif
endif

XPREFIX=/opt/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib

ifeq (1,0)
FFPREFIX=$(P)/development/ffcall
FFLIB=-lavcall
override EXTRACFLAGS+=-DUSE_AVCALL
else
FFPREFIX=$(P)/development/libffi
endif
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib

ifeq ($(SWARMBACKEND),tk)
TCLVERS=8.0
TKVERS=8.0
TCLINCDIR=$(P)/swarm/tcl$(TCLVERS)/include
TKINCDIR=$(P)/swarm/tk$(TKVERS)/include
TCLLIBDIR=$(P)/swarm/tcl$(TCLVERS)/lib/tcl$(TCLVERS)
TKLIBDIR=$(P)/swarm/tk$(TKVERS)/lib/tk$(TKVERS)
BLTVERS=8.0-unoff
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib
BLTLIBRARYDIR=$(BLTPREFIX)/library
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
OTHERINCDIRS=-I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR) # -I/opt/local/include
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(XLIBDIR) -L$(BLTLIBDIR) -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/..
override EXTRALDFLAGS+=-R$(BLTLIBDIR) -R$(TKLIBDIR)/.. -R$(TCLLIBDIR)/.. -R$(FFLIBDIR)
else # AWT backend
override EXTRACFLAGS+=-DUSE_JAVA
JAVALIBDIR=$(JAVA_HOME)/lib/sparc
JAVAINCDIR=$(JAVA_HOME)/include
OTHERINCDIRS=-I$(FFINCDIR) -I$(JAVAINCDIR) -I$(JAVAINCDIR)/solaris -I$(XINCDIR)
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(JAVALIBDIR)/$(JAVA_THREADS)_threads -L$(JAVALIBDIR) -L$(XLIBDIR)
override EXTRALDFLAGS+=-R$(JAVALIBDIR)
JAVAC=$(JAVA_HOME)/bin/javac
endif
endif

ifeq ($(SETUP),alex-SFI-GNU/Linux)
# Alex's SFI GNU/Linux setup

SYS=GNU/Linux
ifeq ($(SWARMCOMPILER),gcc)
CC=/usr/bin/gcc
#OTHERLIBS=-lc
TCLVERS=8.0
TKVERS=8.0
BLTVERS=8.0-unoff
TCLOBJCPREFIX=$(P)/swarm/tclobjc-1.3
else
CC=$(P)/development/egcs/bin/gcc
TCLVERS=7.6
TKVERS=4.2
BLTVERS=2.3
TCLOBJCPREFIX=$(P)/swarm/tclobjc-egcs
endif
OPTFLAGS=-O3 -g
FFPREFIX=$(P)/development/libffi
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
#TCLPREFIX=/usr
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TCLINCDIR=$(TCLPREFIX)/include
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
#TKPREFIX=/usr
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TKINCDIR=$(TKPREFIX)/include
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib
# blt$(BLTVERS)
FFPREFIX=$(P)/development/libffi
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
XPREFIX=/usr/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
ZPREFIX=$(P)/development/zlib
ZLIBDIR=$(ZPREFIX)/lib
ZINCDIR=$(ZPREFIX)/include
PNGPREFIX=$(P)/graphics/png
PNGLIBDIR=$(PNGPREFIX)/lib
PNGINCDIR=$(PNGPREFIX)/include
OTHERINCDIRS=-I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TKINCDIR) -I$(TCLINCDIR) -I$(XINCDIR)  #-I/usr/include
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(XLIBDIR) -L$(BLTLIBDIR) -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKINCDIR)/.. #-L/usr/lib 
override EXTRALDFLAGS+=-Wl,-rpath,$(BLTLIBDIR),-rpath,$(TKLIBDIR)/..,-rpath,$(TCLLIBDIR)/..,-rpath,$(FFLIBDIR),-rpath,$(PNGLIBDIR)

endif

ifeq ($(SETUP),mgd-SFI-Solaris)
SYS=solaris
ifeq ($(SWARMCOMPILER),gcc28)
CC=$(P)/development/gcc/bin/gcc
OPTFLAGS=-mcpu=ultrasparc -O3 -g
override EXTRACFLAGS+=-Werror -Wno-implicit-int
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0-gcc28
else
ifeq ($(SWARMCOMPILER),egcs)
CC=$(P)/development/egcs/bin/gcc -V egcs-2.90.27 # 1.0.2
OPTFLAGS=-mcpu=ultrasparc -O3 -g
override EXTRACFLAGS+=-Werror -Wno-implicit
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0-egcs
else
CC=/opt/gnu/bin/gcc
OPTFLAGS=-O3 -g -mv8
override EXTRACFLAGS+=-Werror
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0-gcc
endif
endif
XPREFIX=/opt/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
ifeq (1,0)
FFPREFIX=$(P)/development/ffcall
FFLIB=-lavcall
override EXTRACFLAGS+=-DUSE_AVCALL
else
FFPREFIX=$(P)/development/libffi
endif
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
ifeq ($(SWARMBACKEND),tk)
TCLVERS=8.0
TKVERS=8.0
TCLINCDIR=$(P)/swarm/tcl$(TCLVERS)/include
TKINCDIR=$(P)/swarm/tk$(TKVERS)/include
TCLLIBDIR=$(P)/swarm/tcl$(TCLVERS)/lib/tcl$(TCLVERS)
TKLIBDIR=$(P)/swarm/tk$(TKVERS)/lib/tk$(TKVERS)
BLTVERS=8.0-unoff
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib
BLTLIBRARYDIR=$(BLTPREFIX)/library
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
PNGPREFIX=$(P)/graphics/png
PNGINCDIR=$(PNGPREFIX)/include
PNGLIBDIR=$(PNGPREFIX)/lib
ZPREFIX=$(P)/development/zlib
ZINCDIR=$(ZPREFIX)/include
ZLIBDIR=$(ZPREFIX)/lib
OTHERINCDIRS=-I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR)
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(BLTLIBDIR) -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/.. -L$(XLIBDIR)
override EXTRALDFLAGS+=-R$(BLTLIBDIR) -R$(TKLIBDIR)/.. -R$(TCLLIBDIR)/.. -R$(FFLIBDIR)
else
override EXTRACFLAGS+=-DUSE_JAVA
JAVALIBDIR=$(JAVA_HOME)/lib/sparc
JAVAINCDIR=$(JAVA_HOME)/include
OTHERINCDIRS=-I$(FFINCDIR) -I$(JAVAINCDIR) -I$(JAVAINCDIR)/solaris -I$(XINCDIR)
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(JAVALIBDIR)/$(JAVA_THREADS)_threads -L$(JAVALIBDIR) -L$(XLIBDIR)
override EXTRALDFLAGS+=-R$(JAVALIBDIR)
JAVAC=$(JAVA_HOME)/bin/javac
endif

#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-SFI-GNU/Linux)
# Marcus' SFI GNU/Linux setup
SYS=GNU/Linux
ifeq ($(SWARMCOMPILER),gcc)
CC=/usr/bin/gcc
TCLVERS=7.4
TKVERS=4.0
BLTVERS=2.1
TCLOBJCPREFIX=$(P)/swarm/tclobjc-old
else
CC=$(P)/development/egcs/bin/gcc
TCLVERS=7.6
TKVERS=4.2
BLTVERS=2.3
TCLOBJCPREFIX=$(P)/swarm/tclobjc-egcs
endif
OPTFLAGS=-O3 -g
FFPREFIX=$(P)/development/libffi
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TCLINCDIR=$(TCLPREFIX)/include
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TKINCDIR=$(TKPREFIX)/include
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib/blt$(BLTVERS)
FFPREFIX=$(P)/development/libffi
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
XPREFIX=/usr/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
ZPREFIX=$(P)/development/zlib
ZLIBDIR=$(ZPREFIX)/lib
ZINCDIR=$(ZPREFIX)/include
PNGPREFIX=$(P)/graphics/png
PNGLIBDIR=$(PNGPREFIX)/lib
PNGINCDIR=$(PNGPREFIX)/include
OTHERINCDIRS=-I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR) # -I/opt/local/include
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(XLIBDIR) -L$(BLTLIBDIR)/.. -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/..
override EXTRALDFLAGS+=-Wl,-rpath,$(BLTLIBDIR)/..,-rpath,$(TKLIBDIR)/..,-rpath,$(TCLLIBDIR)/..,-rpath,$(FFLIBDIR)
endif

ifeq ($(SETUP),mgd-FSF-NetBSD) # Alpha
SYS=NetBSD
CC=gcc
OPTFLAGS=-O3 -g
TCLINCDIR=$(P)/swarm/tcl/include
TKINCDIR=$(P)/swarm/tk/include
BLTPREFIX=$(P)/swarm/blt
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib/blt/blt$(BLTVERS)
XPREFIX=/usr/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
TCLOBJCLIBDIR=$(P)/swarm/tclobjc/lib
TCLOBJCINCDIR=$(P)/swarm/tclobjc/include
TCLVERS=76
TKVERS=42
TCLLIBDIR=$(P)/swarm/tcl/lib/tcl7.6
TKLIBDIR=$(P)/swarm/tk/lib/tk4.2

OTHERINCDIRS=-I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR)
OTHERLIBDIRS=-L$(XLIBDIR) -L$(BLTLIBDIR)/.. -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/..
override EXTRACFLAGS+=-I/usr/local/lib/gcc-lib/alpha-unknown-netbsd1.2D/2.7.2.2/include -Wno-unused
override EXTRALDFLAGS+=-Wl,-rpath,$(P)/swarm/blt/lib,-rpath,$(TKLIBDIR)/..,-rpath,$(TCLLIBDIR)/..,-rpath,$(XLIBDIR)
endif

ifeq ($(SETUP),mgd-PSU-GNU/Linux)
SYS=GNU/Linux
OPTFLAGS=-O3 -g
TCLVERS=7.6
TKVERS=4.2
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TCLINCDIR=$(TCLPREFIX)/include
TKINCDIR=$(TKPREFIX)/include
BLTVERS=2.3
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
ifeq ($(SWARMCOMPILER),gcc28)
CC=$(P)/development/gcc/bin/i586-glibc-linux-gcc -V 2.8.0
OTHERLIBS=-lpthread # For the thread-safe Objective C runtime `posix'.
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
override EXTRACFLAGS+=-Wno-implicit-int -Werror
FFPREFIX=$(P)/development/libffi-glibc
else
ifeq ($(SWARMCOMPILER),gcc28-libc1)
CC=$(P)/development/gcc/bin/i686-pc-linux-gnulibc1-gcc -V 2.8.0
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
override EXTRACFLAGS+=-Wno-implicit-int -Werror
TCLPREFIX=/usr
TKPREFIX=/usr
TCLINCDIR=$(TCLPREFIX)/include/tcl
TKINCDIR=$(TKPREFIX)/include/tcl
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)-libc1
FFPREFIX=$(P)/development/libffi
else
ifeq ($(SWARMCOMPILER),gcc-libc1)
CC=/usr/bin/gcc
TCLOBJCPREFIX=$(P)/swarm/tclobjc
TCLPREFIX=/usr
TKPREFIX=/usr
TCLINCDIR=$(TCLPREFIX)/include/tcl
TKINCDIR=$(TKPREFIX)/include/tcl
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)-libc1
FFPREFIX=$(P)/development/libffi
else
CC=i586-glibc-linux-gcc -V 2.7.2.2
TCLOBJCPREFIX=$(P)/swarm/tclobjc
override EXTRACFLAGS+=-Werror
FFPREFIX=$(P)/development/libffi-glibc
endif
endif
endif
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib/blt$(BLTVERS)
XPREFIX=/usr/X11R6
XINCDIR=$(XPREFIX)/include
XLIBDIR=$(XPREFIX)/lib
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
OTHERINCDIRS=-I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XINCDIR)
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(BLTLIBDIR)/.. -L$(TCLOBJCLIBDIR) -L$(TKLIBDIR)/.. -L$(TCLLIBDIR)/.. -L$(XLIBDIR)
override EXTRALDFLAGS+=-Wl,-rpath,$(BLTLIBDIR)/..,-rpath,$(TKLIBDIR)/..,-rpath,$(TCLLIBDIR)/..,-rpath,$(FFLIBDIR)
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-PSU-Irix5)
SYS=irix53
ifeq ($(SWARMCOMPILER),gcc28)
CC=$(P)/development/gcc/bin/gcc -V 2.8.0
override EXTRACFLAGS+=-Wno-implicit-int -Werror
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
OPTFLAGS=-O3 # -g causes confusion to the archiver, for some reason.
else
CC=$(P)/development/gcc/bin/gcc -V 2.7.2
override EXTRACFLAGS+=-Werror
TCLOBJCPREFIX=$(P)/swarm/tclobjc
OPTFLAGS=-g # gcc-2.7.2 -O3 dies compiling C[24]LCGXgen.m
endif
DISTLDFLAGS=-non_shared
# libffi failed to compile on Irix5
FFPREFIX=$(P)/development/ffcall
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
FFLIB=-lavcall
override EXTRACFLAGS+=-DUSE_AVCALL
TCLVERS=7.6
TKVERS=4.2
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TCLINCDIR=$(TCLPREFIX)/include
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKINCDIR=$(TKPREFIX)/include
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
BLTVERS=2.3
BLTPREFIX=$(P)/swarm/blt$(BLTVERS)
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib/blt$(BLTVERS)
XPMPREFIX=$(P)/X/xpm
XPMINCDIR=$(XPMPREFIX)/include
XPMLIBDIR=$(XPMPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
OTHERINCDIRS=-I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XPMINCDIR)
OTHERLIBDIRS=-L$(FFLIBDIR) -L$(BLTLIBDIR)/.. -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/.. -L$(XPMLIBDIR)
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-LANL-Irix64)
SYS=irix64
CC=$(P)/development/egcs/bin/gcc
override EXTRACFLAGS+=-Wno-implicit-int -Werror
TCLOBJCPREFIX=$(P)/swarm/tclobjc-tcltk8.0
OPTFLAGS=-O3 # -g
DISTLDFLAGS=-non_shared -static
TCLVERS=8.0
TKVERS=8.0
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TCLINCDIR=$(TCLPREFIX)/include
TCLLIBDIR=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKINCDIR=$(TKPREFIX)/include
TKLIBDIR=$(TKPREFIX)/lib/tk$(TKVERS)
BLTPREFIX=$(P)/swarm/blt8.0-unoff
BLTINCDIR=$(BLTPREFIX)/include
BLTLIBDIR=$(BLTPREFIX)/lib
XPMPREFIX=$(P)/X/xpm
XPMINCDIR=$(XPMPREFIX)/include
XPMLIBDIR=$(XPMPREFIX)/lib
TCLOBJCLIBDIR=$(TCLOBJCPREFIX)/lib
TCLOBJCINCDIR=$(TCLOBJCPREFIX)/include
ifeq (1,1)
FFPREFIX=$(P)/development/ffcall
FFLIB=-lavcall
override EXTRACFLAGS+=-DUSE_AVCALL
else
FFPREFIX=$(P)/development/libffi
endif
FFINCDIR=$(FFPREFIX)/include
FFLIBDIR=$(FFPREFIX)/lib
ZPREFIX=$(P)/development/zlib
ZLIBDIR=$(ZPREFIX)/lib
ZINCDIR=$(ZPREFIX)/include
PNGPREFIX=$(P)/graphics/png
PNGLIBDIR=$(PNGPREFIX)/lib
PNGINCDIR=$(PNGPREFIX)/include
OTHERINCDIRS=-I$(PNGINCDIR) -I$(ZINCDIR) -I$(FFINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I$(XPMINCDIR)
OTHERLIBDIRS=-L$(PNGLIBDIR) -L$(ZLIBDIR) -L$(FFLIBDIR) -L$(BLTLIBDIR) -L$(TCLOBJCLIBDIR) -L$(TCLLIBDIR)/.. -L$(TKLIBDIR)/.. -L$(XPMLIBDIR)
override EXTRALDFLAGS+=-Wl,-rpath,$(FFLIBDIR)
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),umich)
SYS=hpux
### the following 6 variables are needed to *make* binary distributions
TCLINCDIR=/usr/local/include/tcl7.4
TKINCDIR=/usr/local/include/tk4.0
BLTINCDIR=/usr/local/blt-2.1/include
BLTLIBDIR=/usr/local/blt-2.1/lib
XINCDIR=/usr/local/include
TCLOBJCINCDIR=/usr/local/include/tclobjc
TKLIBDIR=/usr/local/lib/tk4.0
TCLLIBDIR=/usr/local/lib/tcl7.4
TCLVERS=7.4
TKVERS=4.0

OTHERINCDIRS=-I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(TCLINCDIR) -I$(TKINCDIR) -I/usr/include/X11R5
# OTHERINCDIRS=-I/usr/include/X11R5 -I/usr/local/blt-2.1/include -I/usr/local/include
OTHERLIBDIRS=-L/usr/lib/X11R5  -L/usr/local/blt-2.1/lib -L/usr/local/lib 
endif

ifeq ($(SETUP),nelson)
# Nelson's Linux (RedHat 3.0.3) box (ELF, gcc 2.7.2, libc 5.2.18)
SYS=linux
TCLVERS=7.5
TKVERS=4.1
OTHERINCDIRS=-I/usr/include/tcl
OTHERLIBDIRS=-L/usr/X11R6/lib
endif

ifeq ($(SETUP),glen)
# glen's Linux (Slackware 3.1) box (ELF, gcc 2.7.2, libc 5.3.12)
SYS=linux
CC=gcc
### the following 6 variables are needed to *make* binary distributions

# for 7.5/4.1, I needed Tcl.h, Tk.h, tcl.h, tclObjc.h, tk.h
TCLINCDIR=/usr/include/tcl7.5
TKINCDIR=$(TCLINCDIR)
TCLOBJCINCDIR=$(TCLINCDIR)

BLTINCDIR=/usr/local/blt/include
BLTLIBDIR=/usr/local/blt/lib/blt2.1
XINCDIR=/usr/X11R6/include/X11
TCLLIBDIR=/usr/lib/tcl7.5
TKLIBDIR=/usr/lib/tk4.1
TCLVERS=7.5
TKVERS=4.1

OTHERINCDIRS=-I/usr/include
OTHERLIBDIRS=-L/usr/X11R6/lib -L/usr/lib
SYSDEPLIBS=-ldl
endif

ifeq ($(SETUP),OZ)
# Jane's Alpha
SYS=alpha
CC=gcc
### the following 6 variables are needed to *make* binary distributions

# for 7.5/4.1, I needed Tcl.h, Tk.h, tcl.h, tclObjc.h, tk.h
TCLINCDIR=/usr/local/apps/tcl7.5/include
TKINCDIR=/usr/local/apps/tk4.1b3/include
TCLOBJCINCDIR=/mount/munkora/home/guest/sfi/gepr/xtra/libtclobjc-1.1b7
BLTINCDIR=/usr/local/apps/blt2.1/include
BLTLIBDIR=/usr/local/apps/blt2.1/lib/blt2.1
XINCDIR=/usr/local/X11
TCLLIBDIR=/usr/local/apps/tcl7.5/lib/tcl7.5
TKLIBDIR=/usr/local/apps/tk4.1b3/lib/tk4.1
TCLVERS=7.5
TKVERS=4.1

OTHERINCDIRS=-I$(TCLINCDIR) -I$(TKINCDIR) -I$(TCLOBJCINCDIR) -I$(BLTINCDIR) -I$(XINCDIR)
OTHERLIBDIRS=-L/usr/local/X11/lib  -L/usr/local/apps/tcl7.5/lib -L/usr/local/apps/tk4.1b3/lib -L/usr/local/apps/blt2.1/lib -L/mount/munkora/home/guest/sfi/gepr/xtra/libtclobjc-1.1b6 #-L/usr/local/apps/libtclobjc-1.1b6/lib
SYSDEPLIBS=-lreadline -lcurses #-ldl
endif

ifeq ($(BLTLIBRARYDIR),)
BLTLIBRARYDIR=$(BLTLIBDIR)/../../library
endif

ifeq ($(SYS),solaris)
OTHERINCDIRS := $(OTHERINCDIRS) -I/usr/openwin/include
OTHERLIBDIRS := $(OTHERLIBDIRS) -L/usr/openwin/lib
SYSDEPLIBS=-lsocket -ldl -lnsl
endif

ifeq ($(SYS),GNU/Linux)
SYSDEPLIBS=-ldl
endif

ifeq ($(SYS),HPUX)
SYSDEPLIBS=-ldld
endif

ifeq ($(SYS),irix64)
RANLIB=/bin/true
else
RANLIB=ranlib
endif


##############################################################################
### End of options you should need to configure. You can safely ignore
### everything below here, although experts might want to change these
### definitions (used to compile all swarm code.)

### Swarm code is installed in these three places
LIBDIR=$(SWARMHOME)/lib
INCDIR=$(SWARMHOME)/include
BINDIR=$(SWARMHOME)/bin

###
### In its simplest form, Swarm is compiled into a monolithic
### binary that encapsulates all of the tk/tcl and system files
### needed to link an application.
DISTOBJ=$(LIBDIR)/swarm.x

### These definitions are used for all compiles.
### You can override EXTRACFLAGS and EXTRALDFLAGS easily on the commandline
### Notes about specific flags:
###   -Wall is a good idea: it helps catch some easy errors.
###   -Wno-import turns off an annoying gcc feature
###   -O3 makes a big difference when running Swarm: when you get
###       serious, you want to build Swarm's libraries with optimization
###   -mv8 is a Sparc-specific optimization. On newer sparc chips, multiply
###        and divide (and hence, array access, random number generation, etc)
###        are about 30 times faster. (Old sparc chips will crash, however).
ifeq ($(origin CC),default)
CC=		gcc
endif
WARNFLAGS=	-Wall -Wno-import
ifeq ($(OPTFLAGS),)
OPTFLAGS=	-g -O
endif
ifeq ($(EXTRACFLAGS),)
EXTRACFLAGS=
endif
CFLAGS=$(OPTFLAGS) $(WARNFLAGS) -I$(INCDIR) $(OTHERINCDIRS) $(EXTRACFLAGS)

### All Swarm apps are linked against SWARMLIBS, SYSLIBS, and OTHERLIBS
### in addition, application Makefiles should put extra Swarm libraries
### in APPLIBS. Currently, there is one library you might want in APPLIBS,
### "-lspace". There are also contributed libraries that could go here.
LINKER=		$(CC)
ifeq ($(EXTRALDFLAGS),)
EXTRALDFLAGS=
endif
MINLDFLAGS=	-L$(LIBDIR) $(OTHERLIBDIRS) $(EXTRALDFLAGS)
LDFLAGS=	-g $(MINLDFLAGS)

ifeq ($(SYS),NT)
SYSDEPLIBS=-luser32 -lgdi32
X11LIB=
XPMLIB=
else
X11LIB=-lX11
XPMLIB=-lXpm
endif

ifeq ($(BLTLIB),)
BLTLIB=-lBLT
endif

ifeq ($(FFLIB),)
FFLIB=-lffi
endif

ifeq ($(SWARMBACKEND),tk)
SYSLIBS=-ltclobjc $(BLTLIB) -ltk$(TKVERS) -ltcl$(TCLVERS) $(XPMLIB) -lpng -lz $(FFLIB)
else
SYSLIBS=-ljava_g $(FFLIB)
endif

### Swarm can either be used in an "archive" configuration, where
### you link apps against an archive built from source, or a "bin" 
### configuration where you link apps against a distributed object
### that has most of the user library dependent routines already linked
### into it
ifeq ($(LDCONFIG),bin)
LIBS= $(APPLIBS) $(DISTOBJ) -lobjc $(X11LIB) -lm $(OTHERLIBS) $(SYSDEPLIBS)
else
SWARMLIBS= -lanalysis -lsimtools -lsimtoolsgui -l$(SWARMBACKEND)objc -lactivity -lrandom -lobjectbase -lcollections -ldefobj -lmisc
LIBS= $(APPLIBS) $(SWARMLIBS) $(SYSLIBS) -lobjc $(X11LIB) -lm $(OTHERLIBS) $(SYSDEPLIBS)
endif

### Suffix rules for default compilation.
.SUFFIXES: .m .xm .i

.m.o:
	$(CC) -c $(CFLAGS) $<

.m.i:
	$(CC) -E $(CFLAGS) $< > $@

### Rule to extract types, symbols, classes defined by a library module
.h.xm:
	@CC="$(CC)" CFLAGS="$(CFLAGS)" OBJECTS="$(OBJECTS)" sh $(BINDIR)/make-h2x $@
