### Configure this file so Swarm knows about your environment. Some day
###   we will try to use GNU autoconf to do this for you.

### SETUP:  Canned setup for sites that build architecture-specific.  
### binaries (normal user use NONE and assign values to OTHERLIBDIRS
### and OTHERINCDIRS).  legal values: (NONE,SFI,nelson,umich);

### OTHERINCDIRS needs to be set so Swarm can find X11, tcl, tk, 
###   libtclobjc, and objc include files. Ie, <X11/Xlib.h>, <tcl.h>,
###   and <objc/Object.h> all need to be includable.
###

### OTHERLIBDIRS needs to be set so Swarm can find X11, Tcl, Tk, BLT,
###   tclobjc, and objc libs. Note: we use the file libtcl.a, not libtcl7.4.a
###   Insure that libtcl.a is really tcl7.4, libtk.a is really tk4.0.

### OTHERLIBS are other libraries you might need to link to compile
###   Swarm code. (-lsocket, for instance, or maybe -liberty).

### SYS: Induce canned options for a supported platform.  
### legal values: (solaris,hpux,linux,sgi)

### LDCONFIG: Use the distributed binary Swarm kernel (which has relevant
### portions of several system libraries linked into it), or use the
### local swarm library archives, along with local system libraries.
### legal values: (bin,archive)

ifeq ($(SWARMSETUP),)
# Select your setup here, set SETUP in the environment, or provide
# a value on the command line.
SETUP=SFI
else
SETUP=$(SWARMSETUP)
endif

### for SETUP=NONE
SYS=
OTHERINCDIRS=
OTHERLIBDIRS=
SYSDEPLIBS=

LDCONFIG=archive

ifeq ($(SETUP),SFI)
# SFI's setup
SYS=solaris
### the following 7 variables are needed to *make* binary distributions
CC=gcc
TCLINC=/usr/local/include/tcl7.5
TKINC=/usr/local/include/tk4.1
BLTINC=/opt/local/blt/include
BLTLIB=/opt/local/blt/lib/blt2.1
XINC=/opt/X11R6/include
TCLOBJCINC=/net/user/swarm/support-swarm/libtclobjc-1.1b7
#TCLOBJCINC=/net/user/gepr/Swarm/1.0.3/libtclobjc-1.1b6+
TCLLIB=/usr/local/lib/tcl7.5
TKLIB=/usr/local/lib/tk4.1
TCLVERS=7.5
TKVERS=4.1

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC) -I/opt/local/include
OTHERLIBDIRS=-L/opt/X11R6/lib -L/opt/local/blt/lib -L/opt/local/lib -L$(TCLOBJCINC)
endif

ifeq ($(SETUP),alex-SFI-Solaris)
SYS=solaris
compiler=gcc # egcs
ifeq ($(compiler),gcc28)
CC=$(P)/development/gcc/bin/gcc
OPTFLAGS=-mcpu=ultrasparc -O3 
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
else
ifeq ($(compiler),egcs)
CC=$(P)/development/egcs/bin/gcc
OPTFLAGS= -O3 -mcpu=ultrasparc
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
else
CC=/opt/gnu/bin/gcc
OPTFLAGS=-mv8 -O3
TCLOBJCPREFIX=$(P)/swarm/tclobjc
endif
endif
override EXTRACFLAGS+=-Wno-implicit
BLTINC=$(P)/swarm/blt2.3/include
BLTLIB=$(P)/swarm/blt2.3/lib
XPREFIX=/opt/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLOBJCLIB=$(TCLOBJCPREFIX)/lib
TCLOBJCINC=$(TCLOBJCPREFIX)/include
TCLVERS=7.5
TKVERS=4.1
TCLINC=$(P)/swarm/tcl$(TCLVERS)/include
TKINC=$(P)/swarm/tk$(TKVERS)/include
TCLLIB=$(P)/swarm/tcl$(TCLVERS)/lib/tcl$(TCLVERS)
TKLIB=$(P)/swarm/tk$(TKVERS)/lib/tk$(TKVERS)

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC) # -I/opt/local/include
OTHERLIBDIRS=-L$(XLIB) -L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TCLLIB)/.. -L$(TKLIB)/..
override EXTRALDFLAGS+=-R$(BLTLIB) -R$(TKLIB)/.. -R$(TCLLIB)/.. 

#EXTRACFLAGS+=-pg
#EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-SFI-Solaris)
SYS=solaris
ifeq ($(SWARMCOMPILER),gcc28)
CC=$(P)/development/gcc/bin/gcc
OPTFLAGS=-mcpu=ultrasparc -O3 -g
#OPTFLAGS=-O0
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
else
ifeq ($(SWARMCOMPILER),egcs)
CC=$(P)/development/egcs/bin/gcc
OPTFLAGS=-mcpu=ultrasparc -O3 -g
TCLOBJCPREFIX=$(P)/swarm/tclobjc-new
else
CC=/opt/gnu/bin/gcc
OPTFLAGS=-mv8 -O3 -g
TCLOBJCPREFIX=$(P)/swarm/tclobjc
endif
endif
override EXTRACFLAGS+=-Wno-implicit -Werror
BLTINC=$(P)/swarm/blt2.3/include
BLTLIB=$(P)/swarm/blt2.3/lib
XPREFIX=/opt/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLOBJCLIB=$(TCLOBJCPREFIX)/lib
TCLOBJCINC=$(TCLOBJCPREFIX)/include
TCLVERS=7.5
TKVERS=4.1
TCLINC=$(P)/swarm/tcl$(TCLVERS)/include
TKINC=$(P)/swarm/tk$(TKVERS)/include
TCLLIB=$(P)/swarm/tcl$(TCLVERS)/lib/tcl$(TCLVERS)
TKLIB=$(P)/swarm/tk$(TKVERS)/lib/tk$(TKVERS)

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC) # -I/opt/local/include
OTHERLIBDIRS=-L$(XLIB) -L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TCLLIB)/.. -L$(TKLIB)/..
override EXTRALDFLAGS+=-R$(BLTLIB) -R$(TKLIB)/.. -R$(TCLLIB)/.. 

#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-SFI-GNU/Linux)
# Marcus' SFI GNU/Linux setup
SYS=GNU/Linux
CC=gcc
OPTFLAGS=-O3 -g
TCLINC=$(P)/swarm/tcl/include
TKINC=$(P)/swarm/tk/include
BLTINC=$(P)/swarm/blt/include
BLTLIB=$(P)/swarm/blt/lib
XPREFIX=/usr/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLOBJCLIB=$(P)/swarm/tclobjc/lib
TCLOBJCINC=$(P)/swarm/tclobjc/include
TCLVERS=7.6
TKVERS=4.2
TCLLIB=$(P)/swarm/tcl/lib/tcl$(TCLVERS)
TKLIB=$(P)/swarm/tk/lib/tk$(TKVERS)

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC) # -I/opt/local/include
OTHERLIBDIRS=-L$(XLIB) -L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TCLLIB)/.. -L$(TKLIB)/..
override EXTRALDFLAGS+=-Wl,-rpath,$(BLTLIB),-rpath,$(TKLIB)/..,-rpath,$(TCLLIB)/..
endif

ifeq ($(SETUP),mgd-FSF-NetBSD) # Alpha
SYS=NetBSD
CC=gcc
OPTFLAGS=-O3 -g
TCLINC=$(P)/swarm/tcl/include
TKINC=$(P)/swarm/tk/include
BLTINC=$(P)/swarm/blt/include
BLTLIB=$(P)/swarm/blt/lib
XPREFIX=/usr/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLOBJCLIB=$(P)/swarm/tclobjc/lib
TCLOBJCINC=$(P)/swarm/tclobjc/include
TCLVERS=76
TKVERS=42
TCLLIB=$(P)/swarm/tcl/lib/tcl7.6
TKLIB=$(P)/swarm/tk/lib/tk4.2

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC)
OTHERLIBDIRS=-L$(XLIB) -L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TCLLIB)/.. -L$(TKLIB)/..
override EXTRACFLAGS+=-I/usr/local/lib/gcc-lib/alpha-unknown-netbsd1.2D/2.7.2.2/include -Wno-unused
override EXTRALDFLAGS+=-Wl,-rpath,$(P)/swarm/blt/lib,-rpath,$(TKLIB)/..,-rpath,$(TCLLIB)/..,-rpath,$(XLIB)
endif

ifeq ($(SETUP),mgd-PSU-GNU/Linux-libc5)
SYS=GNU/Linux
CC=/usr/bin/gcc
OPTFLAGS=-O3 -g
TCLINC=/usr/include/tcl
TKINC=$(TCLINC)
BLTPREFIX=$(P)/development/BLT
BLTINC=$(BLTPREFIX)/include
BLTLIB=$(BLTPREFIX)/lib
XPREFIX=/usr/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLOBJCPREFIX=$(P)/development/libtclobjc
TCLOBJCLIB=$(TCLOBJCPREFIX)/lib
TCLOBJCINC=$(TCLOBJCPREFIX)/include
TCLVERS=7.5
TKVERS=4.1
TCLLIB=/usr/lib/$(TCLVERS)
TKLIB=/usr/lib/$(TKVERS)
OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC)
OTHERLIBDIRS=-L$(BLTLIB) -L$(TCLOBJCLIB) -L$(XLIB)
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-PSU-GNU/Linux-glibc2)
SYS=GNU/Linux
CC=i586-glibc-linux-gcc
OPTFLAGS=-O3 -g
override EXTRACFLAGS+=-Wno-implicit
BLTPREFIX=$(P)/swarm/blt2.3
BLTINC=$(BLTPREFIX)/include
BLTLIB=$(BLTPREFIX)/lib
XPREFIX=/usr/X11R6
XINC=$(XPREFIX)/include
XLIB=$(XPREFIX)/lib
TCLVERS=7.6
TKVERS=4.2
TCLPREFIX=$(P)/swarm/tcl$(TCLVERS)
TCLINC=$(TCLPREFIX)/include
TCLLIB=$(TCLPREFIX)/lib/tcl$(TCLVERS)
TKPREFIX=$(P)/swarm/tk$(TKVERS)
TKINC=$(TKPREFIX)/include
TKLIB=$(TKPREFIX)/lib/tk$(TKVERS)
TCLOBJCPREFIX=$(P)/swarm/tclobjc
TCLOBJCINC=$(TCLOBJCPREFIX)/include
TCLOBJCLIB=$(TCLOBJCPREFIX)/lib
OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XINC)
OTHERLIBDIRS=-L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TKLIB)/.. -L$(TCLLIB)/.. -L$(XLIB)
OTHERLIBS=-lpthread # For the thread-safe Objective C runtime `posix'.
override EXTRALDFLAGS+=-Wl,-rpath,$(BLTLIB),-rpath,$(TKLIB)/..,-rpath,$(TCLLIB)/..
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),mgd-PSU-Irix5)
SYS=irix53
CC=gcc
OPTFLAGS=-O3 -g # gcc-2.7.2 -O3 dies compiling C[24]LCGXgen.m
override EXTRACFLAGS+=-Wno-implicit 
TCLINC=$(P)/development/tcl/include
TKINC=$(P)/development/tk/include
BLTPREFIX=$(P)/development/BLT
BLTINC=$(BLTPREFIX)/include
BLTLIB=$(BLTPREFIX)/lib
XPMPREFIX=$(P)/X/xpm
XPMINC=$(XPMPREFIX)/include
XPMLIB=$(XPMPREFIX)/lib
TCLOBJCPREFIX=$(P)/development/libtclobjc
TCLOBJCLIB=$(TCLOBJCPREFIX)/lib
TCLOBJCINC=$(TCLOBJCPREFIX)/include
TCLVERS=7.5
TKVERS=4.1
TCLLIB=$(P)/development/tcl/lib/tcl$(TCLVERS)
TKLIB=$(P)/development/tk/lib/tk$(TKVERS)
OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I$(XPMINC)
OTHERLIBDIRS=-L$(BLTLIB) -L$(TCLOBJCLIB) -L$(TCLLIB)/.. -L$(TKLIB)/.. -L$(XPMLIB)
#override EXTRACFLAGS+=-pg
#override EXTRALDFLAGS+=-pg
endif

ifeq ($(SETUP),umich)
SYS=hpux
### the following 6 variables are needed to *make* binary distributions
TCLINC=$(HOME)/include/tcl7.4
TKINC=$(HOME)/include/tk4.0
BLTINC=/usr/local/blt-2.1/include
BLTLIB=/usr/local/blt-2.1/lib
XINC=/usr/local/include
TCLOBJCINC=$(HOME)/include/tclobjc
TKLIB=/usr/local/lib/tk4.0
TCLLIB=/usr/local/lib/tcl7.4
TCLVERS=7.4
TKVERS=4.0

OTHERINCDIRS=-I$(TCLOBJCINC) -I$(BLTINC) -I$(TCLINC) -I$(TKINC) -I/usr/include/X11R5
# OTHERINCDIRS=-I/usr/include/X11R5 -I/usr/local/blt-2.1/include -I/usr/local/include
OTHERLIBDIRS=-L/usr/lib/X11R5  -L/usr/local/blt-2.1/lib -L/usr/local/lib 
endif

ifeq ($(SETUP),nelson)
# Nelson's Linux (RedHat 3.0.3) box (ELF, gcc 2.7.2, libc 5.2.18)
SYS=linux
TCLVERS=7.5
TKVERS=4.1
OTHERINCDIRS=-I/usr/include/tcl
OTHERLIBDIRS=-L/usr/X11R6/lib
endif

ifeq ($(SETUP),glen)
# glen's Linux (Slackware 3.1) box (ELF, gcc 2.7.2, libc 5.3.12)
SYS=linux
CC=gcc
### the following 6 variables are needed to *make* binary distributions

# for 7.5/4.1, I needed Tcl.h, Tk.h, tcl.h, tclObjc.h, tk.h
TCLINC=/usr/include/tcl7.5
TKINC=$(TCLINC)
TCLOBJCINC=$(TCLINC)

BLTINC=/usr/local/blt/include
BLTLIB=/usr/local/blt/lib/blt2.1
XINC=/usr/X11R6/include/X11
TCLLIB=/usr/lib/tcl7.5
TKLIB=/usr/lib/tk4.1
TCLVERS=7.5
TKVERS=4.1

OTHERINCDIRS=-I/usr/include
OTHERLIBDIRS=-L/usr/X11R6/lib -L/usr/lib
SYSDEPLIBS=-ldl
endif

ifeq ($(SETUP),OZ)
# Jane's Alpha
SYS=alpha

### the following 6 variables are needed to *make* binary distributions

# for 7.5/4.1, I needed Tcl.h, Tk.h, tcl.h, tclObjc.h, tk.h
TCLINC=/usr/local/apps/tcl7.5/include
TKINC=/usr/local/apps/tk4.1b3/include
TCLOBJCINC=/mount/munkora/home/guest/sfi/gepr/xtra/libtclobjc-1.1b6
#TCLOBJCINC=/usr/local/apps/libtclobjc-1.1b6/include
BLTINC=/usr/local/apps/blt2.1/include
BLTLIB=/usr/local/apps/blt2.1/lib/blt2.1
XINC=/usr/local/X11
TCLLIB=/usr/local/apps/tcl7.5/lib/tcl7.5
TKLIB=/usr/local/apps/tk4.1b3/lib/tk4.1
TCLVERS=7.5
TKVERS=4.1

OTHERINCDIRS=-I$(TCLINC) -I$(TKINC) -I$(TCLOBJCINC) -I$(BLTINC) -I$(XINC)
OTHERLIBDIRS=-L/usr/local/X11/lib  -L/usr/local/apps/tcl7.5/lib -L/usr/local/apps/tk4.1b3/lib -L/usr/local/apps/blt2.1/lib -L/mount/munkora/home/guest/sfi/gepr/xtra/libtclobjc-1.1b6 #-L/usr/local/apps/libtclobjc-1.1b6/lib
SYSDEPLIBS=-lreadline -lcurses #-ldl
endif

ifeq ($(SYS),solaris)
OTHERINCDIRS := $(OTHERINCDIRS) -I/usr/openwin/include
OTHERLIBDIRS := $(OTHERLIBDIRS) -L/usr/openwin/lib
SYSDEPLIBS=-lsocket -ldl -lnsl
endif

ifeq ($(SYS),GNU/Linux)
SYSDEPLIBS=-ldl
endif

### If you don't have ranlib on your system (some SysV systems), then set
### this to /bin/true, or anything that ignores its arguments and does nothing
RANLIB=		ranlib

# ifeq ($(SYS),???)
# RANLIB=	/bin/true
# endif


##############################################################################
### End of options you should need to configure. You can safely ignore
### everything below here, although experts might want to change these
### definitions (used to compile all swarm code.)

### Swarm code is installed in these three places
LIBDIR=$(SWARMHOME)/lib
INCDIR=$(SWARMHOME)/include
BINDIR=$(SWARMHOME)/bin

###
### In its simplest form, Swarm is compiled into a monolithic
### binary that encapsulates all of the tk/tcl and system files
### needed to link an application.
DISTOBJ=$(LIBDIR)/swarm.x

### These definitions are used for all compiles.
### You can override EXTRACFLAGS and EXTRALDFLAGS easily on the commandline
### Notes about specific flags:
###   -Wall is a good idea: it helps catch some easy errors.
###   -Wno-import turns off an annoying gcc feature
###   -O3 makes a big difference when running Swarm: when you get
###       serious, you want to build Swarm's libraries with optimization
###   -mv8 is a Sparc-specific optimization. On newer sparc chips, multiply
###        and divide (and hence, array access, random number generation, etc)
###        are about 30 times faster. (Old sparc chips will crash, however).
ifeq ($(CC),)
CC=		gcc
endif
WARNFLAGS=	-Wall -Wno-import
ifeq ($(OPTFLAGS),)
OPTFLAGS=	-g
endif
# OPTFLAGS=	-O3
# OPTFLAGS=	-mv8 -O3
ifeq ($(EXTRACFLAGS),)
EXTRACFLAGS=
endif
CFLAGS=		$(OPTFLAGS) $(WARNFLAGS) -I$(INCDIR) $(OTHERINCDIRS) $(EXTRACFLAGS)

### All Swarm apps are linked against SWARMLIBS, SYSLIBS, and OTHERLIBS
### in addition, application Makefiles should put extra Swarm libraries
### in APPLIBS. Currently, there is one library you might want in APPLIBS,
### "-lspace". There are also contributed libraries that could go here.
LINKER=		$(CC)
ifeq ($(EXTRALDFLAGS),)
EXTRALDFLAGS=
endif
MINLDFLAGS=	-L$(LIBDIR) $(OTHERLIBDIRS) $(EXTRALDFLAGS)
LDFLAGS=	-g $(MINLDFLAGS)

SYSLIBS=        -ltclobjc -lBLT -ltk$(TKVERS) -ltcl$(TCLVERS) -lXpm

### Swarm can either be used in an "archive" configuration, where
### you link apps against an archive built from source, or a "bin" 
### configuration where you link apps against a distributed object
### that has most of the user library dependent routines already linked
### into it
ifeq ($(LDCONFIG),bin)
LIBS= $(DISTOBJ) -lobjc -lX11 -lm $(OTHERLIBS) $(SYSDEPLIBS)
else
SWARMLIBS=      -lanalysis -lsimtools -ltkobjc -lactivity -lrandom -lobjectbase -lcollections -ldefobj
LIBS=		$(APPLIBS) $(SWARMLIBS) $(SYSLIBS) -lobjc -lX11 -lm $(OTHERLIBS) $(SYSDEPLIBS)
endif

### Copy a header file into the installed place.
INSTALLHEADERS=cp -p

### Suffix rules for default compilation.
.SUFFIXES: .m .xm

.m.o:
	$(CC) -c $(CFLAGS) $<

### Rule to extract types, symbols, classes defined by a library module
.h.xm:
	@ CC=$(CC) CFLAGS="$(CFLAGS)" OBJECTS="$(OBJECTS)" $(BINDIR)/make-h2x $@
