EXTRA_DIST = $(MODULE).ent $(MODULE)00.xml $(MODULE)cont.xml $(MODULE)meta.xml
nodist_noinst_DATA = $(MODULE)revhistory.xml

swarm_ChangeLog = $(swarm_srcdir)/src/$(MODULE)/ChangeLog

include $(top_srcdir)/Makefile.common

# Local variables:
# mode: makefile
# end:

