JAVA_SRC = Mousetrap.java MousetrapModelSwarmCImpl.java		\
MousetrapModelSwarmImpl.java MousetrapObserverSwarmCImpl.java	\
MousetrapObserverSwarmImpl.java MousetrapStatistics.java

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)
