JAVA_SRC = Mousetrap.java MousetrapModelSwarmImpl.java			\
MousetrapObserverSwarmCImpl.java MousetrapObserverSwarmImpl.java	\
MousetrapStatistics.java MousetrapBatchSwarmImpl.java

all: $(JAVA_SRC)
	$(SWARMHOME)/bin/javacswarm $(JAVA_SRC)
